# Generated by Django 3.1.1 on 2020-09-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('description', models.CharField(default=0, max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
